### ISSUE TITLE
JSONP use docs could be improved

### ISSUE THREAD

**Issue by n1k0** [cujojs/rest#105]
Following the [docs](https://github.com/cujojs/rest/blob/master/docs/interceptors.md#module-rest/interceptor/jsonp), I naively tried to use the jsonp interceptor that way:

``` js
var client = require("rest").wrap(require("rest/interceptor/jsonp"));

client({
  path: 'http://ajax.googleapis.com/ajax/services/search/web?v=1.0', 
  params: { q: 'javascript' } 
}).then(function(response) {
  console.log("success", response);
}).catch(function(response) {
  console.error("errored", response);
});
```

Though that doesn't work, and won't apply the interceptor at all it seems, resulting in a CORS error in the browser console.

Reading the tests, it appeared that there's a client we can directly use, which works:

``` js
var client = require("rest/client/jsonp");

client({
  path: 'http://ajax.googleapis.com/ajax/services/search/web?v=1.0', 
  params: { q: 'javascript' } 
}).then(function(response) {
  console.log("success", response);
}).catch(function(response) {
  console.error("errored", response);
});
```

I suspect the docs could be improved to avoid readers to mess with the two approaches, and the client module use should definitely be highlighted imho.

**Comment by scothis** [comment]
The behavior of the jsonp interceptor is a little bit different than a typical interceptor because it needs to hijack the normal upstream client and use the jsonp client instead.  When you use `client.wrap()`, the upstream client is automatically passed to the interceptor to use as the next client, which overrides the interceptor's default client.

The usage pattern is more like:
```js
var client = require("rest/interceptor/jsonp")({ ...interceptor config... });

client({
  path: 'http://ajax.googleapis.com/ajax/services/search/web?v=1.0', 
  params: { q: 'javascript' } 
}).then(function(response) {
  console.log("success", response);
}).catch(function(response) {
  console.error("errored", response);
});
```

I agree the docs need to be clearer.

Moving forward, we can consider make the jsonp interceptor more aggressively apply the jsonp client. Basically, instead of using the parent client as the client `.wrap()` was called on, force a custom client to be provided in the interceptor config. Thoughts?

**Comment by n1k0** [comment]
> Basically, instead of using the parent client as the client .wrap() was called on, force a custom client to be provided in the interceptor config. Thoughts?

That would seem more natural to me, indeed.

**Comment by scothis** [comment]
rest.js is no longer maintained
