### ISSUE TITLE
Provide a more straightforward way to cancel requests

### ISSUE THREAD

**Issue by kfranqueiro** [cujojs/rest#118]
It took me a while to figure out that the `cancel` function is defined on the options object that is passed in.  This seems pretty awkward, since it involves modifying user input to the function for the purpose of providing more output in addition to the return value.  It's also impossible to get at the `cancel` function at all if you pass `rest` a string.

It also took me a while to realize that this was what the [docs](https://github.com/cujojs/rest/blob/master/docs/interfaces.md#common-request-properties) meant by "provided" in the table, though that is probably mostly just because my brain didn't want to accept that the input object is being modified for output purposes.

I realize that alternative options are sort of limited...  Returning an object that includes `cancel` and `promise` properties certainly seems like a non-starter since that makes the API far more cumbersome to use for the majority of cases.

The only other thing I can think of is tacking the `cancel` function onto the returned promise, but that would (typically, at least) involve delegating over the object since promises are frozen.  I also have to admit that this is still at least a little bit clunky because you would have to purposely capture the `rest` promise itself in a variable to get at the canceler (i.e. once you chain it, it's lost).

Has anyone had any other thoughts about how to provide a cancel API?

**Comment by scothis** [comment]
Thanks for your thoughts @kfranqueiro. I fully agree that adding a method to an input is a strange place to put functionality.

This may just be semantics, but the properties you pass to the client are the request object. If you think of it as the request instead of options, adding additional behavior is less bad.

Promises do not have a native facility for cancelation, which makes the available solutions a bit hacky and non-interoperable. In rest.js v1.1 we added additional convenience methods to the the promise returned by a client. I'd be in favor of adding a cancel method to [ResponsePromise](https://github.com/cujojs/rest/blob/v1.3.1/util/responsePromise.js#L106-L119) that delegates to the current cancel method on the request. A small gotcha is that the current wrapper is unaware of the request.

Let me know if you'd like to take a stab at implementing.

**Comment by kfranqueiro** [comment]
Oh, I forgot I'd seen that code (and kind of wondered about it since when's code seems to indicate that we shouldn't assume it will hand us unfrozen promises forever).  I imagine I'd need to add an argument to responsePromise`'s APIs, and I'm not sure how much finagling will be required in each place it's used.  I can't say I'll have bandwidth to get to this very soon, but if you're open to it I'll keep it in mind.

**Comment by rleger** [comment]
The cancel method may be what I need to solve my problem : 

My app displays a paginated collection of items, people can browse pages by clicking a "next/prev" button.
If the user clicks multiple times on the 'next' button quickly every new page will fire of a new request. I'd like to make sure that only the latest request gets going and all the other (unfinished) ones are aborted.

I used to do this with a beforeSend method that would add the xhr object to an array and before a request was fired it would call .abort() on all xhr in that array.

I'm using rest now (very new at it), I can't figure out how the cancel method could be used to accomplish that.
Of course I don't want to abort any request before a new one is run, just the ones that tap the same resource as I might have unrelated data loading elsewhere.


/users?page=1
/users?page=1
/users?page=1
/users?page=1


Any help would be very appreciated.

**Comment by scothis** [comment]
rest.js is no longer maintained
