### ISSUE TITLE
interceptor class exist a Asynchronous time-consuming problem

### ISSUE THREAD

**Issue by crixusshen** [cujojs/rest#139]
interceptor class#121: requestHandler.call(context, request, config, meta), If requestHandler is a Asynchronous time-consuming function, Access to the variable 'request' will be 'undefined'

**Comment by scothis** [comment]
@crixusshen can you provide an example that demonstrates the behavior you describe?  All request/response interceptor methods are async and time-consuming since Promises will always resolve in the next tick.

One thing to keep in mind is that you must return the request/response object in the handler. Not returning the request/response would cause it to become undefined.

**Comment by scothis** [comment]
Stale. @crixusshen please reopen if you can show an issue.
