### ISSUE TITLE
interceptor config does not like $ref??

### ISSUE THREAD

**Issue by gogamoga** [cujojs/rest#59]
Refuses to work:
---------------------

```js
define({
    somePrefix: "whatever",
    client: {
        rest: {
            interceptors: [
                {
                    module: "rest/interceptor/pathPrefix",
                    config: {
                      prefix: { $ref: "somePrefix" }
                    }
                }
            ]
        }
    }
})
```

**Comment by briancavalier** [comment]
I think the only similar precedent is `create`.  It [checks specifically for a `$ref`](https://github.com/cujojs/wire/blob/master/lib/plugin/basePlugin.js#L224) in one spot.  In general, I don't think it's a good thing to do, but because the interceptor config will have its own grammar, which could collide with wire's (ie. if we `wire()`d the interceptor config directly), it seems like allowing a `$ref` might be the best solution.

**Comment by scothis** [comment]
With @briancavalier advice taken into account, I'm leaning towards making the config object managed by wire. If there is a conflict between those properties and wire factories, users will have to use the literal factory. Seem fair?

**Comment by briancavalier** [comment]
Seems like a reasonable option to me :)

**Comment by scothis** [comment]
fixed via https://github.com/cujojs/rest/commit/6fa1cacf24cf81d0e7986d4e9f75f24c0e28ada5
