### ISSUE TITLE
Mime type converter gets called twice

### ISSUE THREAD

**Issue by mosch** [cujojs/rest#87]
I have a PATCH request that replies with a 204 and a Location header. 
The library is following the location header by doing a GET request on the location from the header.

But the answer somehow gets passed to the (json) mime converter twice. I only have this behaviour in this request, did a lot of debugging but could find the cause. Solved it with a little 

  if (typeof str == 'object') return str;

in the json mime converter for now. But i think there should be a real fix about this. Any ideas?

**Comment by glennschmidt** [comment]
@scothis As it currently stands, would I be correct in saying that if you are submitting a JSON entity to a web service, you can't use any interceptors that retry failed requests. eg. `retry`, or `oAuth` because on the second attempt, the request entity will be double-encoded?

The problem as I see it is that when these interceptors retry the request, they start the request chain over from the beginning, but using a *request object* that has already been mutated by various interceptors. It seems like the more correct behavior when restarting a request would be to restore the request object to its original/initial state.

**Comment by scothis** [comment]
rest.js is no longer maintained
